# Generated by Django 3.0.2 on 2020-01-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available_bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_bid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Available_bids_table',
            },
        ),
        migrations.CreateModel(
            name='ClosedSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to=None)),
            ],
            options={
                'db_table': 'Closed_session_table',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to=None)),
            ],
            options={
                'db_table': 'Live_session_table',
            },
        ),
        migrations.CreateModel(
            name='Placed_bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_value', models.FloatField()),
            ],
            options={
                'db_table': 'Placed_bids_table',
            },
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('winning_bid_value', models.FloatField(blank=True, null=True)),
                ('winning_product_image', models.ImageField(upload_to=None)),
            ],
            options={
                'db_table': 'Winners_table',
            },
        ),
    ]
