# Generated by Django 3.0.2 on 2020-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='product_dcrp',
            field=models.SlugField(blank='True', max_length=200),
        ),
        migrations.AlterField(
            model_name='available_bids',
            name='available_bid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='closedsession',
            name='product_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='product_image',
            field=models.ImageField(blank='True', upload_to='liveSession/'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='product_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='placed_bids',
            name='bid_value',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='winners',
            name='winning_bid_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='winners',
            name='winning_product_image',
            field=models.ImageField(blank='True', upload_to='winners/'),
        ),
    ]
