# Generated by Django 3.0.2 on 2020-01-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biddd', '0002_auto_20200108_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed_bids',
            name='product',
            field=models.ForeignKey(blank='False', default=1, on_delete=django.db.models.deletion.CASCADE, to='biddd.LiveSession'),
        ),
        migrations.AlterField(
            model_name='closedsession',
            name='product_image',
            field=models.ImageField(blank='True', upload_to='ClosedSession/'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='product_dcrp',
            field=models.TextField(blank='True', max_length=200),
        ),
    ]
