# Generated by Django 3.0.2 on 2020-01-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddd', '0003_auto_20200108_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedSession',
        ),
        migrations.AddField(
            model_name='winners',
            name='winning_product_name',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='winners',
            name='winning_product_price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
