# Generated by Django 3.0.2 on 2020-01-14 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biddd', '0007_paytmhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_bids',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placed_bids',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placed_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
