# Generated by Django 3.0.2 on 2020-01-16 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biddd', '0008_auto_20200114_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
